const constellations = [
	{ name: "Andromeda", short: "and" },
	{ name: "Antlia", short: "ant" },
	{ name: "Apus", short: "aps" },
	{ name: "Aquarius", short: "aqr" },
	{ name: "Aquila", short: "aql" },
	{ name: "Ara", short: "ara" },
	{ name: "Aries", short: "ari" },
	{ name: "Auriga", short: "aur" },
	{ name: "Boötes", short: "boo" },
	{ name: "Caelum", short: "cae" },
	{ name: "Camelopardalis", short: "cam" },
	{ name: "Cancer", short: "cnc" },
	{ name: "Canes Venatici", short: "cvn" },
	{ name: "Canis Major", short: "cma" },
	{ name: "Canis Minor", short: "cmi" },
	{ name: "Capricornus", short: "cap" },
	{ name: "Carina", short: "car" },
	{ name: "Cassiopeia", short: "cas" },
	{ name: "Centaurus", short: "cen" },
	{ name: "Cepheus", short: "cep" },
	{ name: "Cetus", short: "cet" },
	{ name: "Chamaeleon", short: "cha" },
	{ name: "Circinus", short: "cir" },
	{ name: "Columba", short: "col" },
	{ name: "Coma Berenices", short: "com" },
	{ name: "Corona Australis", short: "cra" },
	{ name: "Corona Borealis", short: "crb" },
	{ name: "Corvus", short: "crv" },
	{ name: "Crater", short: "crt" },
	{ name: "Crux", short: "cru" },
	{ name: "Cygnus", short: "cyg" },
	{ name: "Delphinus", short: "del" },
	{ name: "Dorado", short: "dor" },
	{ name: "Draco", short: "dra" },
	{ name: "Equuleus", short: "equ" },
	{ name: "Eridanus", short: "eri" },
	{ name: "Fornax", short: "for" },
	{ name: "Gemini", short: "gem" },
	{ name: "Grus", short: "gru" },
	{ name: "Hercules", short: "her" },
	{ name: "Horologium", short: "hor" },
	{ name: "Hydra", short: "hya" },
	{ name: "Hydrus", short: "hyi" },
	{ name: "Indus", short: "ind" },
	{ name: "Lacerta", short: "lac" },
	{ name: "Leo", short: "leo" },
	{ name: "Leo Minor", short: "lmi" },
	{ name: "Lepus", short: "lep" },
	{ name: "Libra", short: "lib" },
	{ name: "Lupus", short: "lup" },
	{ name: "Lynx", short: "lyn" },
	{ name: "Lyra", short: "lyr" },
	{ name: "Mensa", short: "men" },
	{ name: "Microscopium", short: "mic" },
	{ name: "Monoceros", short: "mon" },
	{ name: "Musca", short: "mus" },
	{ name: "Norma", short: "nor" },
	{ name: "Octans", short: "oct" },
	{ name: "Ophiuchus", short: "oph" },
	{ name: "Orion", short: "ori" },
	{ name: "Pavo", short: "pav" },
	{ name: "Pegasus", short: "peg" },
	{ name: "Perseus", short: "per" },
	{ name: "Phoenix", short: "phe" },
	{ name: "Pictor", short: "pic" },
	{ name: "Pisces", short: "psc" },
	{ name: "Piscis Austrinus", short: "psa" },
	{ name: "Puppis", short: "pup" },
	{ name: "Pyxis", short: "pyx" },
	{ name: "Reticulum", short: "ret" },
	{ name: "Sagitta", short: "sge" },
	{ name: "Sagittarius", short: "sgr" },
	{ name: "Scorpius", short: "sco" },
	{ name: "Sculptor", short: "scl" },
	{ name: "Scutum", short: "sct" },
	{ name: "Serpens", short: "ser" },
	{ name: "Sextans", short: "sex" },
	{ name: "Taurus", short: "tau" },
	{ name: "Telescopium", short: "tel" },
	{ name: "Triangulum", short: "tri" },
	{ name: "Triangulum Australe", short: "tra" },
	{ name: "Tucana", short: "tuc" },
	{ name: "Ursa Major", short: "uma" },
	{ name: "Ursa Minor", short: "umi" },
	{ name: "Vela", short: "vel" },
	{ name: "Virgo", short: "vir" },
	{ name: "Volans", short: "vol" },
	{ name: "Vulpecula", short: "vul" },
  ];
  
  export default constellations;
  